name: Build

on:
  push:
    branches: '**'

jobs:
  binary:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build
